# Generated by Django 3.0.8 on 2020-07-25 10:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('session_name', models.CharField(max_length=500)),
                ('session_location', models.CharField(max_length=200)),
                ('session_description', models.CharField(max_length=500)),
                ('session_file', models.FileField(blank=True, null=True, upload_to='session_files/')),
                ('session_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Amount should be more than 0')])),
            ],
        ),
    ]
