# Generated by Django 3.0.8 on 2020-07-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
    ]
