# Generated by Django 3.0.8 on 2020-07-25 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_task_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hpu',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Amount should be more than 0')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_total_hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Amount should be more than 0')]),
        ),
    ]
