# Generated by Django 3.0.8 on 2020-07-25 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('available', models.BooleanField(default=False)),
                ('hours_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Amount should be more than 0')])),
            ],
        ),
    ]
