# Generated by Django 3.0.8 on 2020-07-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Task')),
            ],
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
