# Generated by Django 3.0.8 on 2020-07-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20200726_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttask',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
    ]
