# Generated by Django 3.0.8 on 2020-07-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WSSomen',
            new_name='Women',
        ),
    ]
