# Generated by Django 3.0.8 on 2020-07-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_auto_20200725_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='img',
            field=models.FileField(default='default.jpg', upload_to='media/profile_pics'),
        ),
    ]
