# Generated by Django 3.0.8 on 2020-07-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_women_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='mail',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
