# Generated by Django 3.0.8 on 2020-07-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_auto_20200725_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='progression',
            name='locationp',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='progression',
            name='curr_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.Task'),
        ),
    ]
