# Generated by Django 3.0.8 on 2020-07-25 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_auto_20200725_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='women',
            name='hours_available',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Amount should be more than 0')]),
        ),
    ]
